import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { openStateStoreSync } from "../dist/state/store.js";
import { ControlRepository } from "../dist/control/repository.js";
import { AutonomousControlEngine } from "../dist/control/engine.js";
import { InternalMergeService } from "../dist/control/merge.js";
import { ControlPlaneService } from "../dist/control/service.js";

const hash=(c,n=64)=>c.repeat(n); const wait=()=>new Promise(r=>setTimeout(r,20));
function fixture(readinessOverride={}){const dir=mkdtempSync(join(tmpdir(),"b102-"));const store=openStateStoreSync(join(dir,"state.db"));const repository=new ControlRepository(store.db);let now=1_800_000_000_000,starts=0;const engine=new AutonomousControlEngine({repository,ownerId:"worker",leaseTtlMs:60_000,now:()=>now});const provider={inspect:async()=>{throw new Error("unused")},merge:async()=>{throw new Error("unused")},verifyMerged:async()=>false};const mergeService=new InternalMergeService(store.db,repository,provider,()=>now);const service=new ControlPlaneService({db:store.db,repository,engine,mergeService,now:()=>now,crystallise:async()=>({kind:"brief",brief:{title:"Bounded feature",motivation:"Implement safely",acceptanceCriteria:["tested"],filesLikelyTouched:["src/**"],outOfScope:["secrets/**"],repoHint:"o/r",riskLevel:"medium"}}),resolveRepository:async()=>({repositoryIdentity:"o/r",baseRef:"main",baseRevision:hash("a",40),credentialRoute:"vault/o/U1",policyDigest:hash("b"),securityClass:"medium"}),executeEngine:async input=>{starts++;const head=hash("d",40);return{finalVerdict:"pass",blockingFindings:0,reviewCompleted:true,verificationProbes:{completed:1,required:1,indeterminate:0},candidateSha:head,publication:{sha:head,observedAt:now},pullRequest:{repository:"o/r",baseRef:"main",headSha:head,open:true,number:3,url:"https://example.test/pr/3"},expectedRepository:"o/r",expectedBaseRef:"main",requiredCi:{registered:true,requiredChecks:["test"],successfulChecks:["test"],sha:head,status:"success"},runtimeEvidence:{status:"not_required"},securityEvidence:{status:"pass"},elapsedTimeMs:100,timeLimitMs:input.timeLimitSeconds*1000,changedPaths:["src/x.ts"],allowedScope:input.scope,excludedScope:input.excludedScope,operationsPerformed:["implement","test","commit","push_feature_branch","open_pull_request"],allowedOperations:["implement","retry","repair","test","commit","push_feature_branch","open_pull_request","update_pull_request","deploy"],credentialRouteDigest:input.credentialRouteDigest,expectedCredentialRouteDigest:input.credentialRouteDigest,secretExposure:{detected:false,evidence:"pass"},spendUsd:2,budgetUsd:input.budgetUsd,...readinessOverride};}});const context=(att)=>({requesterSenderId:"U1",conversationId:"W:C:T",...(att?{trustedControlAttestation:att}:{})});const attest=(id,event="confirm")=>{const run=repository.getRun(id);const p=store.db.prepare("SELECT created_at FROM control_proposals WHERE run_id=?").get(id);now=Math.max(now+10,p.created_at+10,run.updatedAt+10);const a={version:2,provenance:"host_verified",operation:"confirm_change",actorIdentity:"U1",conversationIdentity:"W:C:T",hostEventId:event,nonce:`${event}-nonce`,issuedAt:now,expiresAt:now+60000,bindingDigest:""};a.bindingDigest=service.confirmBindingDigest(id,a);return a;};return{dir,store,repository,service,context,attest,starts:()=>starts,close(){store.close();rmSync(dir,{recursive:true,force:true})}};}

test("beta102: confirmation starts once and has no clarification/resume state",async()=>{const f=fixture();try{const p=await f.service.prepare({request:"Implement it",repository:"o/r",scope:["src/**"],excludedScope:["secrets/**"],budgetUsd:7,timeLimitSeconds:900},f.context());assert.equal(p.state,"prepared");await f.service.confirm(p.changeId,f.context(f.attest(p.changeId)));await wait();assert.equal(f.starts(),1);assert.equal(f.repository.getRun(p.changeId).state,"pr_ready");assert.deepEqual(f.repository.listStateEvents(p.changeId).map(e=>e.toState),["draft","awaiting_confirmation","autonomous_run","pr_ready"]);assert.ok(!f.repository.listStateEvents(p.changeId).some(e=>/clarif|pause|resume/i.test(`${e.toState} ${e.reason}`)));}finally{f.close();}});

test("beta102: a post-confirmation scope escalation is terminal",async()=>{const f=fixture({changedPaths:["outside/x.ts"]});try{const p=await f.service.prepare({request:"Implement it",repository:"o/r",scope:["src/**"]},f.context());await f.service.confirm(p.changeId,f.context(f.attest(p.changeId,"scope")));await wait();const run=f.repository.getRun(p.changeId);assert.equal(run.state,"failed");assert.equal(run.terminalCode,"scope_exceeded");assert.equal(f.service.result(p.changeId,f.context()).state,"failed");}finally{f.close();}});

test("beta102: confirmation replay never dispatches duplicate work",async()=>{const f=fixture();try{const p=await f.service.prepare({request:"Implement it",repository:"o/r"},f.context());const a=f.attest(p.changeId,"once");await f.service.confirm(p.changeId,f.context(a));await assert.rejects(()=>f.service.confirm(p.changeId,f.context(a)),/already confirmed|already_confirmed|can no longer be confirmed/i);await wait();assert.equal(f.starts(),1);}finally{f.close();}});
