/**
 * beta.114: keep a repo's generated tree out of a feature commit.
 *
 * The b113 DR/BCP run shipped PR #961 with 154 changed files. Thirteen were the
 * feature -- schema, migration, five API routes, a page, an upload component,
 * tests. The other 141 were `okf/**`, ProjectThanos's generated documentation
 * bundle, regenerated by a worker as a side effect and swept up by the unscoped
 * `git add -A`.
 *
 * The adversary saw it and filed `codebase-fit`/`info`, twice, in two separate
 * cycles. `info` blocks nothing, so it was never cleaned up. The PR came out
 * CONFLICTING against main, and every review cycle had 141 files of unrelated
 * surface to find new things in -- a plausible reason findings went 20 -> 12 ->
 * 16 instead of converging.
 *
 * These tests run against REAL git, because the mechanism is entirely about
 * git's own staging semantics: b110's `.git/info/exclude` list cannot do this
 * job, since git consults it only for untracked files and `okf/` is 1,496
 * TRACKED files. A mock would have happily "passed" the broken approach.
 */

import test from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdtempSync, writeFileSync, mkdirSync, rmSync, existsSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { GitAdapter } from "../dist/adapters/git-worktree.js";

const QUIET = { info() {}, warn() {}, error() {} };

function git(cwd, ...args) {
  return execFileSync("git", ["-C", cwd, ...args], {
    encoding: "utf8",
    env: { ...process.env, GIT_CONFIG_GLOBAL: "/dev/null", GIT_CONFIG_SYSTEM: "/dev/null" },
  }).trim();
}

/** A repo with a tracked generated tree and tracked feature code, like ProjectThanos. */
function makeRepo() {
  const dir = mkdtempSync(join(tmpdir(), "oah-b114-"));
  git(dir, "init", "-q", "-b", "main");
  git(dir, "config", "user.name", "Test");
  git(dir, "config", "user.email", "test@example.com");
  git(dir, "config", "commit.gpgsign", "false");
  mkdirSync(join(dir, "okf/libraries/it"), { recursive: true });
  mkdirSync(join(dir, "src/app"), { recursive: true });
  writeFileSync(join(dir, "okf/libraries/it/a.md"), "generated a\n");
  writeFileSync(join(dir, "okf/libraries/it/b.md"), "generated b\n");
  writeFileSync(join(dir, "okf/index.md"), "generated index\n");
  writeFileSync(join(dir, "src/app/page.tsx"), "export const Page = () => null;\n");
  git(dir, "add", "-A");
  git(dir, "commit", "-q", "-m", "base");
  return dir;
}

function adapter(neverCommitPaths) {
  return new GitAdapter({
    worktreesRoot: mkdtempSync(join(tmpdir(), "oah-b114-wt-")),
    logger: QUIET,
    bootstrapDeps: false,
    neverCommitPaths,
  });
}

const ID = { name: "Harness", email: "harness@example.com" };
/** Files touched by the commit at HEAD. */
const committedFiles = (dir) => git(dir, "show", "--name-only", "--pretty=format:", "HEAD").split("\n").filter(Boolean);

const repos = [];
const fresh = () => {
  const d = makeRepo();
  repos.push(d);
  return d;
};
test.after(() => {
  for (const d of repos) rmSync(d, { recursive: true, force: true });
});

test("beta114: the DR/BCP shape -- feature code commits, the regenerated bundle does not", async () => {
  const dir = fresh();
  // A worker edits the feature AND regenerates the bundle as a side effect.
  writeFileSync(join(dir, "src/app/page.tsx"), "export const Page = () => 'feature';\n");
  writeFileSync(join(dir, "okf/libraries/it/a.md"), "REGENERATED a\n");
  writeFileSync(join(dir, "okf/libraries/it/b.md"), "REGENERATED b\n");
  writeFileSync(join(dir, "okf/index.md"), "REGENERATED index\n");

  const sha = await adapter(["okf/**"]).commit(dir, "feat: the actual work", ID);
  assert.ok(sha, "the commit must still happen");
  assert.deepEqual(committedFiles(dir), ["src/app/page.tsx"], "only the feature file belongs in this commit");
});

test("beta114: the bundle is left clean, so the next sub-task cannot re-stage it", async () => {
  const dir = fresh();
  writeFileSync(join(dir, "src/app/page.tsx"), "one\n");
  writeFileSync(join(dir, "okf/index.md"), "REGENERATED\n");
  const a = adapter(["okf/**"]);
  await a.commit(dir, "first", ID);

  // Unstaging alone would leave this dirty and the NEXT `add -A` would sweep it
  // in -- which is how one regeneration becomes 141 files across a whole run.
  assert.equal(git(dir, "status", "--porcelain"), "", "the worktree must be clean after the revert");
  assert.equal(readFileSync(join(dir, "okf/index.md"), "utf8"), "generated index\n", "the file is restored, not merely unstaged");

  writeFileSync(join(dir, "src/app/page.tsx"), "two\n");
  await a.commit(dir, "second", ID);
  assert.deepEqual(committedFiles(dir), ["src/app/page.tsx"], "the second commit must not carry the bundle either");
});

test("beta114: a commit of ONLY excluded paths becomes a no-op, not an empty commit", async () => {
  const dir = fresh();
  writeFileSync(join(dir, "okf/index.md"), "REGENERATED\n");
  const before = git(dir, "rev-parse", "HEAD");
  const sha = await adapter(["okf/**"]).commit(dir, "bundle only", ID);
  assert.equal(sha, null, "nothing of substance changed, so there is nothing to commit");
  assert.equal(git(dir, "rev-parse", "HEAD"), before, "HEAD must not move");
});

test("beta114: with no configuration the behaviour is exactly as before", async () => {
  const dir = fresh();
  writeFileSync(join(dir, "src/app/page.tsx"), "feature\n");
  writeFileSync(join(dir, "okf/index.md"), "REGENERATED\n");
  await adapter(undefined).commit(dir, "everything", ID);
  assert.deepEqual(
    committedFiles(dir).sort(),
    ["okf/index.md", "src/app/page.tsx"],
    "an unconfigured repo must see no change in behaviour; this is opt-in",
  );
});

test("beta114: an empty list is inert", async () => {
  const dir = fresh();
  writeFileSync(join(dir, "okf/index.md"), "REGENERATED\n");
  await adapter([]).commit(dir, "everything", ID);
  assert.deepEqual(committedFiles(dir), ["okf/index.md"]);
});

test("beta114: only the configured tree is dropped", async () => {
  const dir = fresh();
  mkdirSync(join(dir, "okfizz"), { recursive: true });
  writeFileSync(join(dir, "okfizz/keep.md"), "not the bundle\n");
  writeFileSync(join(dir, "okf/index.md"), "REGENERATED\n");
  writeFileSync(join(dir, "src/app/page.tsx"), "feature\n");
  await adapter(["okf/**"]).commit(dir, "work", ID);
  const files = committedFiles(dir).sort();
  assert.ok(files.includes("okfizz/keep.md"), "a same-prefix sibling directory must not be caught");
  assert.ok(files.includes("src/app/page.tsx"));
  assert.ok(!files.includes("okf/index.md"));
});

test("beta114: a NEW file created inside the excluded tree is dropped too", async () => {
  const dir = fresh();
  // Regeneration adds files as well as changing them. An untracked one has
  // nothing to `git restore --worktree` from, which fails the whole pathspec
  // invocation -- so the unstage must stand on its own.
  writeFileSync(join(dir, "okf/libraries/it/new.md"), "brand new generated file\n");
  writeFileSync(join(dir, "src/app/page.tsx"), "feature\n");
  const sha = await adapter(["okf/**"]).commit(dir, "work", ID);
  assert.ok(sha, "the commit must still succeed");
  assert.deepEqual(committedFiles(dir), ["src/app/page.tsx"], "a new generated file must not be committed");
  assert.ok(existsSync(join(dir, "okf/libraries/it/new.md")), "an untracked file is left on disk, just uncommitted");
});

test("beta114: a DELETED file inside the excluded tree is restored", async () => {
  const dir = fresh();
  rmSync(join(dir, "okf/libraries/it/a.md"));
  writeFileSync(join(dir, "src/app/page.tsx"), "feature\n");
  await adapter(["okf/**"]).commit(dir, "work", ID);
  assert.deepEqual(committedFiles(dir), ["src/app/page.tsx"]);
  assert.ok(existsSync(join(dir, "okf/libraries/it/a.md")), "the deletion must be undone, not committed");
});

test("beta114: multiple patterns are all honoured", async () => {
  const dir = fresh();
  mkdirSync(join(dir, "generated"), { recursive: true });
  writeFileSync(join(dir, "generated/schema.json"), "{}\n");
  git(dir, "add", "-A");
  git(dir, "commit", "-q", "-m", "add second generated tree");
  writeFileSync(join(dir, "generated/schema.json"), '{"regenerated":true}\n');
  writeFileSync(join(dir, "okf/index.md"), "REGENERATED\n");
  writeFileSync(join(dir, "src/app/page.tsx"), "feature\n");
  await adapter(["okf/**", "generated/**"]).commit(dir, "work", ID);
  assert.deepEqual(committedFiles(dir), ["src/app/page.tsx"]);
});

test("beta114: the config field survives a parse and is absent by default", async () => {
  const { parseHarnessConfig } = await import("../dist/config.js");
  const base = { slack: { authorised_users: ["U1"] }, repos: { allowed: ["owner/repo"] } };
  assert.equal(parseHarnessConfig(base).repos.never_commit_paths, undefined, "opt-in, so absent by default");
  const cfg = parseHarnessConfig({ ...base, repos: { allowed: ["owner/repo"], never_commit_paths: ["okf/**"] } });
  assert.deepEqual(cfg.repos.never_commit_paths, ["okf/**"]);
});
