import test from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
const { applyStateMigrations } = await import("../dist/state/migrations.js");
const { evaluatePrReadiness } = await import("../dist/control/readiness.js");
const { TERMINAL_AUTHORITY_CODES, AUTONOMOUS_CONTINUATION_KINDS } = await import("../dist/control/engine.js");
test("control storage preserves accounting, readiness, dispatch, checkpoint and merge evidence",()=>{const db=new DatabaseSync(":memory:");applyStateMigrations(db);for(const t of ["control_runs","control_proposals","control_dispatch_intents","control_engine_decisions","control_readiness_results","control_readiness_attestations","control_verified_checkpoints","control_engine_merge_intents","control_merge_authorizations"])assert.equal(db.prepare("SELECT count(*) n FROM sqlite_master WHERE type='table' AND name=?").get(t).n,1,t);db.close();});
test("autonomous retries and repairs stay internal while envelope violations are terminal",()=>{for(const k of ["retry","repair","verification_retry","review_repair"])assert.ok(AUTONOMOUS_CONTINUATION_KINDS.includes(k));for(const c of ["budget_exceeded","time_exceeded","scope_escalation","path_violation"])assert.ok(TERMINAL_AUTHORITY_CODES.includes(c));});
test("strict publication combines review, CI, runtime, security, scope, credentials and spend",()=>{const h="a".repeat(40),d="b".repeat(64);const x={finalVerdict:"pass",blockingFindings:0,reviewCompleted:true,verificationProbes:{completed:1,required:1,indeterminate:0},candidateSha:h,publication:{sha:h,observedAt:1},pullRequest:{repository:"o/r",baseRef:"main",headSha:h,open:true},expectedRepository:"o/r",expectedBaseRef:"main",requiredCi:{registered:true,requiredChecks:["ci"],successfulChecks:["ci"],sha:h,status:"success"},runtimeEvidence:{status:"pass",sha:h,observedAt:1},securityEvidence:{status:"pass",sha:h,observedAt:1},elapsedTimeMs:1,timeLimitMs:10,changedPaths:["src/a"],allowedScope:["src"],excludedScope:[],operationsPerformed:["test"],operationReceipts:[{operation:"test",observedAt:1,source:"test-fixture"}],allowedOperations:["test"],credentialRouteDigest:d,expectedCredentialRouteDigest:d,secretExposure:{detected:false,evidence:"pass"},spendUsd:1,budgetUsd:2};assert.equal(evaluatePrReadiness(x).ready,true);});
