import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { authorCiWorkflow } from "../dist/adapters/ci-workflow.js";
import { createPullRequest, postPrComment } from "../dist/adapters/github.js";
import { evaluatePrReadiness } from "../dist/control/readiness.js";
import { openStateStoreSync } from "../dist/state/store.js";
import { ControlRepository } from "../dist/control/repository.js";
import { AutonomousControlEngine } from "../dist/control/engine.js";
import { InternalMergeService } from "../dist/control/merge.js";
import { ControlPlaneService } from "../dist/control/service.js";

const root=resolve(dirname(fileURLToPath(import.meta.url)),"..");
const sha=(c,n=64)=>c.repeat(n);
const head=sha("a",40),route=sha("b");
const ready=(over={})=>({finalVerdict:"pass",blockingFindings:0,reviewCompleted:true,verificationProbes:{completed:1,required:1,indeterminate:0},candidateSha:head,publication:{sha:head,observedAt:100},pullRequest:{repository:"o/r",baseRef:"main",headSha:head,open:true},expectedRepository:"o/r",expectedBaseRef:"main",requiredCi:{registered:true,requiredChecks:["test"],successfulChecks:["test"],sha:head,status:"success"},runtimeEvidence:{status:"pass",sha:head,observedAt:110},securityEvidence:{status:"pass",sha:head,observedAt:110},elapsedTimeMs:1,timeLimitMs:1000,readinessTimeoutMs:50,changedPaths:["src/x.ts"],allowedScope:["src/**"],excludedScope:[],operationsPerformed:["test"],operationReceipts:[{operation:"test",observedAt:110,sha:head,source:"durable"}],allowedOperations:["test"],credentialRouteDigest:route,expectedCredentialRouteDigest:route,secretExposure:{detected:false,evidence:"pass"},spendUsd:1,budgetUsd:2,...over});

test("workflow authoring checks live authority immediately before write and commit",async()=>{const d=mkdtempSync(join(tmpdir(),"ci-auth-"));try{writeFileSync(join(d,"package.json"),JSON.stringify({scripts:{test:"node --test"}}));let commits=0;await assert.rejects(()=>authorCiWorkflow({worktreePath:d,gitCommit:async()=>{commits++;return head},assertMutationAuthorized:(mutation)=>{if(mutation==="write")throw new Error("authority_expired")}}),/authority_expired/);assert.equal(existsSync(join(d,".github/workflows/harness-ci.yml")),false);assert.equal(commits,0);const order=[];await assert.rejects(()=>authorCiWorkflow({worktreePath:d,gitCommit:async()=>{order.push("commit");return head},assertMutationAuthorized:(mutation)=>{order.push(`authorize:${mutation}`);if(mutation==="commit")throw new Error("scope_denied")}}),/scope_denied/);assert.deepEqual(order,["authorize:write","authorize:commit"]);assert.equal(commits,0);}finally{rmSync(d,{recursive:true,force:true})}});

test("every live workflow path forwards the mutation authority hook",()=>{const source=readFileSync(join(root,"src/orchestrator/legacy-loop.ts"),"utf8");assert.equal((source.match(/assertMutationAuthorized:/g)??[]).length,2);assert.match(source,/mutation === "write" \? "implement" : "commit"/);assert.match(source,/err instanceof ConfirmedControlAuthorityError/);});

test("readiness fails closed for absent, stale, future, pre-publication, or wrong-SHA security receipts",()=>{for(const securityEvidence of [{status:"pass",sha:head},{status:"pass",sha:head,observedAt:149},{status:"pass",sha:head,observedAt:201},{status:"pass",sha:head,observedAt:99},{status:"pass",sha:sha("c",40),observedAt:110}]){const out=evaluatePrReadiness(ready({securityEvidence}),200);assert.equal(out.ready,false);assert.ok(out.failures.includes("security_evidence_indeterminate"));}assert.equal(evaluatePrReadiness(ready(),150).ready,true);});

test("GitHub create, label, and comment mutations reacquire credentials at the request boundary",async()=>{const original=globalThis.fetch;const events=[];globalThis.fetch=async(url,init={})=>{events.push(`fetch:${init.method??"GET"}:${url}`);if(String(url).endsWith("/pulls"))return new Response(JSON.stringify({number:1,html_url:"https://example/pr/1",node_id:"n"}),{status:201,headers:{"content-type":"application/json"}});if(String(url).includes("/labels"))return new Response("{}",{status:200});if(String(url).includes("/comments"))return new Response(JSON.stringify({html_url:"https://example/comment"}),{status:201,headers:{"content-type":"application/json"}});return new Response("[]",{status:200,headers:{"content-type":"application/json"}})};try{let generation=0;const refresh=async()=>{events.push(`credential:${++generation}`);return{ghToken:`t${generation}`,apiBase:"https://api.example"}};await createPullRequest({repoFullName:"o/r",head:"b",base:"main",title:"t",body:"b",ghToken:"stale",labels:["safe"],refreshCredential:refresh});await postPrComment({repoFullName:"o/r",prNumber:1,body:"review",ghToken:"stale",refreshCredential:refresh,apiBase:"https://api.example"});assert.deepEqual(events.map(x=>x.split(":")[0]),["credential","fetch","credential","fetch","credential","fetch"]);let calls=0;await assert.rejects(()=>createPullRequest({repoFullName:"o/r",head:"b",base:"main",title:"t",body:"b",ghToken:"stale",refreshCredential:async()=>{throw new Error("credential_route_changed")}}),/credential_route_changed/);assert.equal(calls,0);}finally{globalThis.fetch=original}});

function serviceFixture(){const dir=mkdtempSync(join(tmpdir(),"control-atomic-")),store=openStateStoreSync(join(dir,"s.db")),repository=new ControlRepository(store.db);let now=1_800_000_000_000;const engine=new AutonomousControlEngine({repository,ownerId:"w",leaseTtlMs:60000,now:()=>now});let service;const mergeService=new InternalMergeService(store.db,repository,{inspect:async()=>{throw new Error("provider down")},merge:async()=>{throw new Error("unused")},verifyMerged:async()=>false},()=>now);service=new ControlPlaneService({db:store.db,repository,engine,mergeService,now:()=>now,crystallise:async()=>({kind:"brief",brief:{title:"x",motivation:"bounded change",acceptanceCriteria:["tested"],filesLikelyTouched:["src/**"],outOfScope:[],repoHint:"o/r",riskLevel:"medium"}}),resolveRepository:async()=>({repositoryIdentity:"o/r",baseRef:"main",baseRevision:sha("d",40),credentialRoute:"route",policyDigest:sha("e"),securityClass:"medium"}),executeEngine:async(input)=>ready({expectedRepository:"o/r",pullRequest:{repository:"o/r",baseRef:"main",headSha:head,open:true,number:1,url:"https://example/pr/1"},allowedScope:input.scope,expectedCredentialRouteDigest:input.credentialRouteDigest,credentialRouteDigest:input.credentialRouteDigest,publication:{sha:head,observedAt:now},runtimeEvidence:{status:"pass",sha:head,observedAt:now},securityEvidence:{status:"pass",sha:head,observedAt:now},operationReceipts:[{operation:"test",observedAt:now,sha:head,source:"durable"}]})});const context=(att)=>({requesterSenderId:"U",conversationId:"C",...(att?{trustedControlAttestation:att}:{})});const attest=(op,id,event)=>{const run=repository.getRun(id),p=store.db.prepare("SELECT created_at FROM control_proposals WHERE run_id=?").get(id);now=Math.max(now+10,p.created_at+10,run.updatedAt+10);const a={version:2,provenance:"host_verified",operation:op,actorIdentity:"U",conversationIdentity:"C",hostEventId:event,nonce:`${event}-n`,issuedAt:now,expiresAt:now+60000,bindingDigest:""};a.bindingDigest=op==="confirm_change"?service.confirmBindingDigest(id,a):service.mergeBindingDigest(id,a);return a};return{dir,store,repository,service,context,attest,close(){service.dispose();store.close();rmSync(dir,{recursive:true,force:true})}}}

test("confirmation transaction rolls back attestation, state, event, and intent together",async()=>{const f=serviceFixture();try{const p=await f.service.prepare({request:"do it",repository:"o/r"},f.context());const att=f.attest("confirm_change",p.changeId,"confirm-atomic");f.store.db.exec(`CREATE TRIGGER fail_dispatch BEFORE INSERT ON control_dispatch_intents BEGIN SELECT RAISE(ABORT,'dispatch fault'); END;`);await assert.rejects(()=>f.service.confirm(p.changeId,f.context(att)),/dispatch fault/);assert.equal(f.repository.getRun(p.changeId).state,"awaiting_confirmation");assert.equal(f.store.db.prepare("SELECT count(*) n FROM control_host_attestations").get().n,0);assert.equal(f.store.db.prepare("SELECT count(*) n FROM control_dispatch_intents").get().n,0);f.store.db.exec("DROP TRIGGER fail_dispatch");await f.service.confirm(p.changeId,f.context(att));assert.equal(f.store.db.prepare("SELECT count(*) n FROM control_dispatch_intents").get().n,1);}finally{f.close()}});

test("merge setup is atomic and provider failure becomes durable merge_failed",async()=>{const f=serviceFixture();try{const p=await f.service.prepare({request:"do it",repository:"o/r"},f.context());await f.service.confirm(p.changeId,f.context(f.attest("confirm_change",p.changeId,"confirm-merge-atomic")));await new Promise(r=>setTimeout(r,20));const att=f.attest("merge_change",p.changeId,"merge-atomic");f.store.db.exec(`CREATE TRIGGER fail_merge_intent BEFORE INSERT ON control_engine_merge_intents BEGIN SELECT RAISE(ABORT,'intent fault'); END;`);await assert.rejects(()=>f.service.merge(p.changeId,f.context(att)),/intent fault/);assert.equal(f.repository.getRun(p.changeId).state,"pr_ready");assert.equal(f.store.db.prepare("SELECT count(*) n FROM control_host_attestations WHERE operation_kind='merge_change'").get().n,0);f.store.db.exec("DROP TRIGGER fail_merge_intent");await assert.rejects(()=>f.service.merge(p.changeId,f.context(att)),/merge failed/i);const result=f.service.result(p.changeId,f.context());assert.equal(result.state,"merge_failed");assert.equal(result.code,"merge_failed");assert.equal(f.store.db.prepare("SELECT status FROM control_engine_merge_intents").get().status,"merge_failed");}finally{f.close()}});
