import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { evaluatePrReadiness } from "../dist/control/readiness.js";
import { createAuthorityEnvelope, evaluateAuthority } from "../dist/control/authority.js";

const root=resolve(dirname(fileURLToPath(import.meta.url)),"..");
const source=(p)=>readFileSync(resolve(root,p),"utf8");
const sha=(c,n=40)=>c.repeat(n);
function ready(over={}){const head=sha("a"),route=sha("b",64);return{finalVerdict:"pass",blockingFindings:0,reviewCompleted:true,verificationProbes:{completed:1,required:1,indeterminate:0},candidateSha:head,publication:{sha:head,observedAt:10},pullRequest:{repository:"o/r",baseRef:"main",headSha:head,open:true,number:1,url:"https://example/pr/1"},expectedRepository:"o/r",expectedBaseRef:"main",requiredCi:{registered:true,requiredChecks:["test"],successfulChecks:["test"],sha:head,status:"success"},runtimeEvidence:{status:"pass",sha:head,observedAt:11},securityEvidence:{status:"pass",sha:head,observedAt:12},elapsedTimeMs:10,timeLimitMs:100,changedPaths:["src/a.ts"],allowedScope:["src/**"],excludedScope:[],operationsPerformed:["test"],operationReceipts:[{operation:"test",observedAt:13,sha:head,source:"provider_receipt"}],allowedOperations:["test"],credentialRouteDigest:route,expectedCredentialRouteDigest:route,secretExposure:{detected:false,evidence:"pass"},spendUsd:1,budgetUsd:2,...over};}

test("readiness rejects inferred or wrong-SHA evidence",()=>{for(const over of [{operationReceipts:[]},{runtimeEvidence:{status:"pass"}},{securityEvidence:{status:"pass",sha:sha("c"),observedAt:12}},{operationReceipts:[{operation:"test",observedAt:13,sha:sha("d"),source:"provider_receipt"}]}]){const result=evaluatePrReadiness(ready(over),20);assert.equal(result.ready,false);}});

test("authority enforces expiry, aggregate limits, and glob-scoped paths",()=>{const envelope=createAuthorityEnvelope({version:1,requesterId:"U",conversationId:"C",repository:"o/r",baseRef:"main",briefDigest:sha("a",64),policyDigest:sha("b",64),scope:{paths:["src/**"]},allowedActions:["implement","retry"],limits:{budgetUsd:2,activeTimeMs:100,cycles:2,retries:1},issuedAt:1,expiresAt:200,nonce:"n"});const base={requesterId:"U",conversationId:"C",repository:"o/r",baseRef:"main",briefDigest:sha("a",64),policyDigest:sha("b",64),nonce:"n",action:"implement",paths:["src/a.ts"],projectedBudgetUsd:1,projectedActiveTimeMs:50,projectedCycles:1,projectedRetries:0,now:100};assert.equal(evaluateAuthority(envelope,base).outcome,"approve");assert.equal(evaluateAuthority(envelope,{...base,now:201}).reason,"expired");assert.equal(evaluateAuthority(envelope,{...base,projectedRetries:2}).reason,"retry_expansion");assert.equal(evaluateAuthority(envelope,{...base,paths:["docs/a.md"]}).reason,"path_out_of_scope");});

test("production wiring binds credentials per provider operation and atomically fences readiness",()=>{const index=source("src/index.ts"),service=source("src/control/service.ts"),loop=source("src/orchestrator/legacy-loop.ts");assert.match(index,/resolveBoundControlCredential/);assert.match(index,/credential_route_binding_missing/);assert.match(index,/boundProviderCredential\("test"\)/);assert.match(index,/controlCredentialRouteDigest\(boundRoute\)/);assert.match(service,/persistDispatchCompletion/);assert.match(service,/BEGIN IMMEDIATE/);assert.match(service,/control_readiness_attestations/);assert.match(service,/control_dispatch_intents SET status=/);assert.match(loop,/worktree_preserved=1,clarification_question=NULL/);assert.match(loop,/COUNT\(\*\) AS retries FROM provider_calls/);assert.doesNotMatch(index,/publication:\s*\{\s*sha:\s*String\(proposal\.published_sha\),\s*observedAt:\s*Date\.now\(\)/);});
