import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
const root=resolve(dirname(fileURLToPath(import.meta.url)),".."); const read=(p)=>readFileSync(resolve(root,p),"utf8");
const registration=read("src/tools/registration.ts"), service=read("src/control/service.ts"), readiness=read("src/control/readiness.ts"), merge=read("src/control/merge.ts"), migrations=read("src/state/migrations.ts"), index=read("src/index.ts");
const expected=["harness_change_result","harness_confirm_change","harness_merge_change","harness_prepare_change"];
async function surface(){const {registerHarnessTools}=await import(pathToFileURL(resolve(root,"dist/tools/registration.js")));const tools=[],commands=[];const api={logger:{info(){},warn(){},error(){}},registerTool(d){tools.push(typeof d==="function"?d({requesterSenderId:"U1",conversationId:"C1"}):d);return()=>{}},registerCommand(d){commands.push(d);return()=>{}}};registerHarnessTools(api,{});return{tools,commands};}
test("ordinary catalog is exactly prepare/confirm/result/merge",async()=>{const {tools,commands}=await surface();assert.deepEqual(tools.map(x=>x.name).sort(),expected);assert.deepEqual(commands,[]);});
test("retired interaction tools are not registered",()=>{for(const name of ["harness_answer","harness_progress","harness_resume","harness_revise","harness_run","harness_onboard"])assert.doesNotMatch(registration,new RegExp(`name:\\s*[\"']${name}`));});
test("one canonical control_runs state machine backs public tools",()=>{assert.match(service,/ControlRepository/);assert.match(migrations,/CREATE TABLE control_proposals/);assert.match(migrations,/DROP TABLE IF EXISTS control_changes/);assert.doesNotMatch(service,/control_changes/);assert.doesNotMatch(service,/control_execution_intents/);});
test("confirmation requires independently verified host provenance and complete binding",()=>{assert.match(service,/provenance:\s*"host_verified"/);assert.match(service,/control-plane-confirm\/v2/);for(const field of ["baseRevision","briefDigest","policyDigest","scope","excludedScope","credentialRouteDigest","budgetUsd","timeLimitMs"])assert.match(service,new RegExp(field));assert.match(registration,/trustedControlAttestation:\s*context\.trustedControlAttestation/);assert.doesNotMatch(registration,/Object\.assign\(\{\}, call\.context, context\)/);});
test("dispatch is durable, leased, fenced, recoverable and stale completions are rejected",()=>{for(const token of ["control_dispatch_intents","lease_fence","lease_expires_at","assertCurrent","stale_dispatch","recoverDispatches"])assert.match(service,new RegExp(token));assert.match(service,/validateLease/);});
test("single normative readiness evaluator enforces every readiness dimension",()=>{for(const token of ["pr_identity_mismatch","required_ci_unregistered","required_ci_not_green","runtime_evidence_indeterminate","security_evidence_indeterminate","elapsed_time_exceeded","scope_exceeded","operation_not_authorized","credential_route_changed","secret_exposure","spend_exceeded"])assert.match(readiness,new RegExp(token));assert.match(service,/engine\.evaluateReadiness/);assert.match(migrations,/control_readiness_attestations/);assert.match(migrations,/UNIQUE\(run_id, generation\)/);});
test("merge revalidates exact head and readiness before provider mutation",()=>{for(const token of ["expectedHeadSha","publishedSha","readinessDigest","evaluatePrReadiness","provider\.inspect","provider\.verifyMerged","merge_provider_idempotency"])assert.match(merge,new RegExp(token));assert.doesNotMatch(service,/runtime\.mergePr/);assert.match(index,/expectedHeadSha/);});
test("private repository base resolution uses the resolved token without logging it",()=>{assert.match(index,/Authorization:\s*`Bearer \$\{token\}`/);assert.doesNotMatch(index,/Authorization:\s*`Bearer \*\*\*`/);assert.doesNotMatch(index,/logger\.[a-z]+\([^\n]*token\b[^\n]*\$\{token\}/i);});
test("public metadata contains no interactive operating protocol",async()=>{const {tools}=await surface();const text=JSON.stringify(tools.map(({name,description,parameters})=>({name,description,parameters})));assert.doesNotMatch(text,/clarification|sub-?task|poll|worktree|harness_(answer|progress|resume|revise|run|onboard)/i);});
