import test from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { basename, join } from "node:path";
function makePackage(root,version,legacy=false){mkdirSync(root,{recursive:true});writeFileSync(join(root,"package.json"),JSON.stringify({name:"openclaw-agent-harness",version,type:"module",files:legacy?["openclaw.plugin.json","skills"]:["openclaw.plugin.json"]}));writeFileSync(join(root,"openclaw.plugin.json"),JSON.stringify({skills:[]}));if(legacy){mkdirSync(join(root,"skills/retired"),{recursive:true});writeFileSync(join(root,"skills/retired/SKILL.md"),"retired interaction skill\n");}}
function pack(root,dest){const out=execFileSync("npm",["pack","--silent","--pack-destination",dest],{cwd:root,encoding:"utf8"}).trim();return join(dest,basename(out.split(/\r?\n/).at(-1)));}
test("upgrade removes retired packaged skills and manifest remains empty",()=>{const temp=mkdtempSync(join(tmpdir(),"oah-no-skills-"));try{const old=join(temp,"old"),next=join(temp,"next"),tar=join(temp,"tar"),install=join(temp,"install");mkdirSync(tar);mkdirSync(install);makePackage(old,"2.0.0-rc.12",true);makePackage(next,"2.0.0-rc.13",false);writeFileSync(join(install,"package.json"),JSON.stringify({private:true}));execFileSync("npm",["install","--ignore-scripts","--omit=dev",pack(old,tar)],{cwd:install});execFileSync("npm",["install","--ignore-scripts","--omit=dev",pack(next,tar)],{cwd:install});const root=join(install,"node_modules/openclaw-agent-harness");assert.equal(JSON.parse(readFileSync(join(root,"package.json"),"utf8")).version,"2.0.0-rc.13");assert.deepEqual(JSON.parse(readFileSync(join(root,"openclaw.plugin.json"),"utf8")).skills,[]);assert.equal(existsSync(join(root,"skills")),false);}finally{rmSync(temp,{recursive:true,force:true});}});
