import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { getGitLabCiSnapshot, getGitLabMergeRequest, getGitLabMergeRequestFiles, getGitLabRevision, mergeGitLabMergeRequest } from "../dist/adapters/gitlab.js";

const root=resolve(import.meta.dirname,"..");
test("GitLab control-plane routes use GitLab projects, MRs, pipelines, changes and merge semantics",async()=>{const original=globalThis.fetch,calls=[];globalThis.fetch=async(url,init={})=>{calls.push({url:String(url),init});const u=String(url);if(u.includes("/repository/commits/"))return new Response(JSON.stringify({id:"a".repeat(40)}),{status:200});if(u.endsWith("/merge_requests/7")&&(!init.method||init.method==="GET"))return new Response(JSON.stringify({sha:"b".repeat(40),state:"opened",target_branch:"main",source_branch:"harness/x",web_url:"https://gitlab.test/o/r/-/merge_requests/7"}),{status:200});if(u.includes("/pipelines?"))return new Response(JSON.stringify([{id:1,status:"success"}]),{status:200});if(u.endsWith("/merge_requests/7/changes"))return new Response(JSON.stringify({changes:[{new_path:"src/a.ts",diff:"@@"}]}),{status:200});if(u.endsWith("/merge_requests/7/merge"))return new Response(JSON.stringify({state:"merged",merge_commit_sha:"c".repeat(40)}),{status:200});throw new Error(`unexpected ${u}`)};try{assert.equal(await getGitLabRevision({repoFullName:"o/r",ref:"main",token:"t",apiBase:"https://gitlab.test/api/v4"}),"a".repeat(40));assert.equal((await getGitLabMergeRequest({repoFullName:"o/r",prNumber:7,token:"t",apiBase:"https://gitlab.test/api/v4"})).headSha,"b".repeat(40));assert.equal((await getGitLabCiSnapshot({repoFullName:"o/r",sha:"b".repeat(40),token:"t",apiBase:"https://gitlab.test/api/v4"})).state,"success");assert.deepEqual(await getGitLabMergeRequestFiles({repoFullName:"o/r",prNumber:7,token:"t",apiBase:"https://gitlab.test/api/v4"}),[{filename:"src/a.ts",status:"modified",patch:"@@"}]);assert.equal((await mergeGitLabMergeRequest({repoFullName:"o/r",prNumber:7,token:"t",apiBase:"https://gitlab.test/api/v4",expectedHeadSha:"b".repeat(40)})).sha,"c".repeat(40));const text=calls.map(c=>c.url+" "+JSON.stringify(c.init)).join("\n");assert.doesNotMatch(text,/\/repos\/|\/pulls\/|\/actions\/|X-GitHub-Api-Version|application\/vnd\.github/);const merge=calls.at(-1);assert.equal(merge.init.method,"PUT");assert.match(String(merge.init.body),/sha=b{40}/);assert.match(String(merge.init.body),/squash=true/);}finally{globalThis.fetch=original}});

test("runtime execution is gated by verified snapshots and repository policy precedes credential routing",()=>{const claude=readFileSync(resolve(root,"src/adapters/claude-code.ts"),"utf8"),router=readFileSync(resolve(root,"src/adapters/backend-router.ts"),"utf8"),index=readFileSync(resolve(root,"src/index.ts"),"utf8");assert.match(claude,/Claude runtime integrity verification has not succeeded/);assert.equal((claude.match(/pathToClaudeCodeExecutable: mandatoryClaudeExecutable\(\)/g)??[]).length,3);assert.match(router,/verifyOpenCodeRuntime/);const block=index.slice(index.indexOf("resolveRepository: async"),index.indexOf("executeEngine: async"));assert.ok(block.indexOf("isRepoAllowed")<block.indexOf("pat.resolve"));assert.ok(block.indexOf("pat.resolve")<block.indexOf("resolveGitToken"));});
